[build]
  command = "npm run build:prod"
  publish = "build"

[[redirects]]
  from = "/login"
  to = "https://ulbi-production-project-server-chi.vercel.app/login"
  status = 200
  force = true

[[redirects]]
  from = "/articles/*"
  to = "https://ulbi-production-project-server-chi.vercel.app/articles/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/articles"
  to = "https://ulbi-production-project-server-chi.vercel.app/articles"
  status = 200
  force = true

[[redirects]]
  from = "/comments/*"
  to = "https://ulbi-production-project-server-chi.vercel.app/comments/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/comments"
  to = "https://ulbi-production-project-server-chi.vercel.app/comments"
  status = 200
  force = true

[[redirects]]
  from = "/profile/*"
  to = "https://ulbi-production-project-server-chi.vercel.app/profile/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "https://ulbi-production-project-server-chi.vercel.app/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
